### ISSUE TITLE
Azure settings: automate the generation of web.config and app.config files

### ISSUE THREAD

**Issue by olivierbloch** [MSOpenTech/connectthedots#117]
In the Website project and in the devices projects, it would be useful to have a pre-build task that prompt the user for its Azure credentials and proposes a "wizzard" to select the event hub name and connection strings without having to enter them manually in the config files.

**Comment by spyrossak** [comment]
fixed in several commits and closed in 86f0be3d53a79ac91f81a99855eb7f75c7f19e58
