### ISSUE TITLE
User ID not recognized

### ISSUE THREAD

**Issue by RubenvWyk** [MSOpenTech/connectthedots#125]
Hi all,

Just started on this and for some reason I am getting this error...

"We don't recognize the User ID or Password"

I have already completed these steps:

Microsoft Azure subscription (free trial subscription is sufficient)
Access to the Azure Streaming Analytics Preview
Visual Studio 2013 – Community Edition

and these:

Open the ConnectTheDots\Azure\AzurePrep\AzurePrep.sln solution in Visual Studio and build the project from the BUILD menu (Select Release, not Debug).
Run the application (hitting F5 in Visual Studio or double clicking on the connectthedots\Azure\AzurePrep\AzurePrep\bin\Release\azureprep.exe file)

Any idea why this might be happening? I tried the program when signed in and out of Azure in my browser... no luck :/

Any help would be appreciated. TIA

Regards,
Ruben

**Comment by dinarisio** [comment]
Hello Ruben,

Could you please confirm that:

    The user account isn't locked out.
    The password isn't a temporary password. (This issue may occur if the user account is a new account or if the password was recently reset.)
    You're not blocked from signing in.
    If you're a federated user, single sign-on (SSO) is working. 
(referring to https://support.microsoft.com/en-us/kb/2412085)

Thanks,
Dinar

**Comment by RubenvWyk** [comment]
Hi Dinar,

Thanks for the quick response.

Confirmed :)

I can log in through my browser just fine. I can access Streaming Analytics as well...

**Comment by RubenvWyk** [comment]
https://support.microsoft.com/en-us/kb/2853347

This is not the solution either

**Comment by dinarisio** [comment]
Was your password requested while running AzurePrep or the message pops right after the start?

**Comment by RubenvWyk** [comment]
This is the first screen that pops up when I run AzurePrep.exe

![problemsigningin](https://cloud.githubusercontent.com/assets/11629690/6801298/0d02abee-d22f-11e4-9e0b-867b93dc425d.png)

**Comment by RubenvWyk** [comment]
Hmmmmmm do I maybe need Azure AD configured?

**Comment by dinarisio** [comment]
I know there could be an issue when library can't recognize what auth page to show to you. (similar issue here http://stackoverflow.com/questions/28074068/cant-use-my-microsoft-account-to-log-into-my-test-app-using-active-directory).
As a workaround, could you please try to enter smth@live.com, and when it redirect you to another login page, just enter correct mail?
Also, seems like some auth data is still being cached, because system not trying to do any redirect to correct page.

**Comment by RubenvWyk** [comment]
w00t!

Thank you!

:)
