### ISSUE TITLE
Add IP address of data source on website

### ISSUE THREAD

**Issue by spyrossak** [MSOpenTech/connectthedots#132]
Add IP address of data source (as precise as possible) and show it when hovering over sensor name on website

**Comment by dinarisio** [comment]
Is additional JSON field assumed here?

**Comment by olivierbloch** [comment]
I think this cannot be done without the up address being sent on the Json.
Du we really want this info to be added on the stream? I would argue that this is not a good thing.
Why do we need this?

Sent from my Windows Phone
________________________________

**Comment by spyrossak** [comment]
My thought is that if we could see the IP address (e.g. by hovering over the name of the device on the chart) then we would be able to access the device remotely if we needed to update it. Lacking a device registry, this seems like the only option.

One JSON field that is currently specified but not used anywhere is ‘location’. A compromise might be to have the website display the location data from the JSON (if not empty) when a user hovers over the device name. We could then have the sensor fill that field with anything we want, e.g. street address, or IP address if desired. A stronger position would be for the gateway to add the gateway’s IP address to that JSON field if it arrives from the sensor unpopulated.

Thoughts?

Sent from Windows Mail

**Comment by dinarisio** [comment]
I will add showing location on hover and add config parameter to gateway- user will able to add ip or not. However, it is not always possible for gateway to get proper ip - for example, socket client had address 127.0.0.1 by default, which is useless here.

**Comment by spyrossak** [comment]
Maybe have flag in gateway config file that says "append gateway ip to sensor location", and have gateway add its ip address to whatever is sent by the sensor in the location field?

Sent from my Windows Phone
________________________________

**Comment by dinarisio** [comment]
Yes, this flag is what i am talking about. As enhancement gateway could add ip of client if request was made throught REST web interface.

**Comment by dinarisio** [comment]
locationIP branch:
Added showing location tip of device on hover.
Added appending string to location by gateway. This string is not ip yet - we need to decide how to get this ip. Service could have many ip's, and one we choose could different from one we use to ssh. Maybe add ip string to config as well?

**Comment by spyrossak** [comment]
For now, write gwy IP on Eth0 to string

Sent from my Windows Phone
________________________________

**Comment by dinarisio** [comment]
updated

**Comment by dinarisio** [comment]
Merged to master.
