### ISSUE TITLE
Deleting, then attempting to recreate a namespace using the AzurePrep project causes the namespace creation process to hang

### ISSUE THREAD

**Issue by devhammer** [MSOpenTech/connectthedots#138]
I'm preparing for another demo of the CTD project tomorrow, and I encountered, for the second time, an issue with the namespace creation process. Because the Streaming Analytics preview does not appear to support the US East data center, where I had pointed the AzurePrep project initially, I had to delete the namespace and event hubs that I created, and re-create them in US East 2.

When I ran the AzurePrep project the second time, and attempted to create a namespace with the same name as I used initially, the namespace creation process hung, with the console app repeatedly printing:

"Namespace [NAMESPACENAME]-ns in state Activating. Waiting..."

and the management portal showing the namespace in "Activating" state. As of writing this, the portal is still showing this after more than a half hour of waiting. The last time this occurred, I was eventually able to delete the namespace, but for the moment, the management portal does not even show that option.

I can't tell at this point whether moving from one datacenter to another is a necessary part of the repro, but here are the rough steps:

1. Run the AzurePrep app, and create the namespace in the desired subscription and datacenter.
2. Delete the newly-created namespace from the Azure management portal.
3. Run the AzurePrep app again, and attempt to create a namespace of the same name as step 1, in a different datacenter (I used US East initially, and US East 2 the second time).

As additional information, if I kill the console window that is showing the hung namespace activation, and run the AzurePrep app again, using a different namespace name, but the same datacenter as where the hang occurred, the namespace creation works normally, and completes almost instantly.

**Comment by devhammer** [comment]
Update. An hour later, the hung namespace is finally active, and able to be deleted.

**Comment by dinarisio** [comment]
Tried to do the same and get this long activating too. Looks like Azure's internal specific - AzurePrep just shows status requsted from Azure, and it actually the same as shown at management portal, used to test it deleted from portal as well as from ClearResources tool. Unfortunally, do not have an idea whether it is by design or not, but most likely is.
