### ISSUE TITLE
Please upload a complete video tutorial of it who is successful in doing this URGENT HELP !!

### ISSUE THREAD

**Issue by shubhkmr** [MSOpenTech/connectthedots#141]
I executed deploy.cmd command it seems that everything is fine there and it connected the pi (i guess ) i stopped with 3 second after that i checked my pi log files and no raspberrypi log file is there apart from booting.log in logs folder (ctdgtwy) 
Please help urgently!!

![iot](https://cloud.githubusercontent.com/assets/11982170/7189635/d7714540-e49d-11e4-8559-d17ab64bae0e.png)
![iot2](https://cloud.githubusercontent.com/assets/11982170/7189637/dc439302-e49d-11e4-9a48-9f197814a338.png)

**Comment by dinarisio** [comment]
Hello. Did you chaged /etc/rc.local as said in documentation?

**Comment by shubhkmr** [comment]
Yes

**Comment by shubhkmr** [comment]
@dinarisio yes I did

**Comment by shubhkmr** [comment]
@dinarisio please help me dude

**Comment by dinarisio** [comment]
@shubhkmr could you list all files/folders you have in home/pi/staging directory?

**Comment by shubhkmr** [comment]
a. Everything in the "GatewayService\WindowsService\bin\Release\" folder
       b. DeviceAdapters\SerialPort\bin\Release\Microsoft.ConnectTheDots.SerialPortAdapter.dll
       c. DeviceAdapters\Socket\bin\Release\Microsoft.ConnectTheDots.SocketAdapter.dll
       d. Scripts\RaspberryPi\Modified\certificate_update.sh
       e. Scripts\RaspberryPi\Modified\autorun_install.sh
       f.  Scripts\RaspberryPi\Modified\kill_all.sh
