### ISSUE TITLE
Web site websocketconnect error

### ISSUE THREAD

**Issue by mpilant** [MSOpenTech/connectthedots#143]
I'm trying to do a test deployment, and have almost everything working.  I've done the Azure Prep, got the code on the device (Intel Galileo), and published the website.  However, when the website comes up, I see all the header, "Live Sensor Data" and everything, but at the end of the page is the message:

ERROR [object Event]
Connecting to ws://lmpcdtwa2.azurewebsites.net/api/websocketconnect?clientId=none

Looking at the Azure portal, there does indeed seem to be a server error, but there isn't a lot of information to help me resolve the problem.

Any ideas?  Thanks in advance.

- Mark

**Comment by dinarisio** [comment]
Hello Mark,

It looks like connection string is not correct, did you done CreateWebConfig part as well and updated your web.config file?

Dinar

**Comment by mpilant** [comment]
Yes.  After doing the AzurePrep, I did the CreateWebConfig to generate the web.config.  I then replaced the web.config in the ConnectTheDotsWebSite solution prior to running the solution to create the website.  It appears the web site got created correctly, and I can seen data being sent from the Galileo to Azure, but the website appears to be having troubles.

- Mark

**Comment by mpilant** [comment]
The connection string used is:

<add key="Microsoft.ServiceBus.ConnectionString" value="Endpoint=sb://lmpcdt2-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey={the key}" />

Curiously, the example here: https://github.com/MSOpenTech/connectthedots/blob/master/Azure/WebSite/WebsitePublish.md

Has SharedSecretIssuer and SharedSecretValue tags rather than the ones actually used in the web.config.  I don't know if this is a problem or simple reflects a update made to the example.

- Mark

**Comment by dinarisio** [comment]
Did you enable WebSockets for the site?

**Comment by mpilant** [comment]
Yes.  WebSockets were/are enabled.

**Comment by mpilant** [comment]
Another data point.  In Visual Studio (2013 Ultimate) if I right click on the project in the solution explorer, and choose View -> View in Browser, IE does fire up a new window and is able to connect to the local website.

- Mark

**Comment by mpilant** [comment]
Yet another piece of data.  In VS, in the Publish Web window, in the connection information, when I click on "Validate Connection", the validation succeeds.  So that raises the obvious question: why does the connection succeed from within VS, and yet fail from IE?

- Mark

**Comment by mpilant** [comment]
Solved.

The problem is the result of not using SSL to access the website.  In other words, referencing the website using HTTP fails but referencing the website using HTTPS succeeds.

Not at all obvious.

- Mark

**Comment by Muhammad-Fir** [comment]
Hi Mark, do you mind telling how you referenced the website using HTTPS? I am currently facing the same problems as you. There is currently no data captured on the website that I deployed. Been stuck at this error for days. Would appreciate it if you could help. Thanks.

**Comment by mpilant** [comment]
Sure.  Instead of using the various links (which do not use SSL, notably the "Start Preview" in the Visual Studio "Publish Web") provided to get to the website I changed the HTTP to HTTPS in the URL.  For example, if I clicked on "Start Preview" the URL http://my-name.azurewebsites.net was accessed in the browser.  This brought up the basic web page, but no information.  By changing the URL to https://my-name.azurewebsites.net, the web page along with the correct information was displayed.

I hope this helps.

- Mark

**Comment by Muhammad-Fir** [comment]
Hi Mark, I have changed the website from HTTP to HTTPS in the URL. The connection status at the bottom has vanished but there is currently no live data captured.

**Comment by mpilant** [comment]
With the connection status error gone, your published website should be able to get the device data.  You should make sure Web Sockets are enabled for your web app.  You might also double / triple check the connection strings.  I've had both of these cause me problems as I was trying to get things working.

- Mark

**Comment by Muhammad-Fir** [comment]
Hi Mark, thanks for the tip. Just a quick question. For your connection string (Shared Access Key), was there an '=' sign at the end of the key? Just curious because that may be the problem.
Thanks.

**Comment by mpilant** [comment]
My SharedAccessKeys all have an equal sign ("=") at the end.  Another thought.  I spent a lot of time going nowhere until I realized the "User" in the .config file was actually "WebSite" and not something else.  (With the password being the SharedAccessKey.)  I also read the ConnectTheDots instructions *many* times, occasionally discovering something I was doing wrong because I misread / misinterpreted the directions.
- Mark

**Comment by Muhammad-Fir** [comment]
Hi Mark, I see. I will check again. By the way, if you change the connection string value, do you have to re-publish the website again?

**Comment by mpilant** [comment]
You shouldn't have to republish.  The change from HTTP to HTTPS only affects the way you would connect to the web site.

- Mark

**Comment by Muhammad-Fir** [comment]
Hi Mark, I have done everything yet there is no data displayed on the website. I have checked the connectionstring many times and I have confirmed that the data is captured by Event Hubs. The only problem is that no data is shown on the website.

**Comment by Muhammad-Fir** [comment]
Hi Mark, data is finally shown on the website yesterday. But the data captured is quite slow. As in I have to wait for a while before the weather shield captures data and send to the website. Do you know why?

**Comment by mpilant** [comment]
I'm glad to hear data is finally appearing.  (Did you do anything to get it to appear or did it just start appearing?)

The most obvious point to check would on the device getting the data from the weather shield.  If I remember correctly, the example code is supposed to send the data every second.  Check to make sure the loop delay is correct.

Beyond that it could be anywhere.  One way to help narrow it down would be to use a network monitor (e.g., Wireshark) to monitor the network traffic originating from the device (gateway).  I would suggest monitoring using a MAC address instead of an IP address to capture all the traffic.  This would tell you if the data is being sent, how often, and if there were any transmission / retransmission issues.

I haven't done anything with mine for quite a while, but at the time I was not seeing any delays,

- Mark

**Comment by Muhammad-Fir** [comment]
Hi Mark, I see, Thanks for the help. Appreciate it.
