### ISSUE TITLE
Missing Web.config file in Azure/WebSite/ConnectTheDotsWebSite/

### ISSUE THREAD

**Issue by shijiong** [MSOpenTech/connectthedots#162]
Hello, When i download the project, and found that web.config file in Azure/WebSite/ConnectTheDotsWebSite/ is missing. And we only have web.debug.config and  web.release.config

**Comment by JohnMeng** [comment]
Please read websitepublish.md 

I think you need run AzurePrep at first

**Comment by shijiong** [comment]
Thanks for your quick reply. I've resolved this problem.
However, After i completed the AzurePrep, i run Windows Phone application and WenSite application. I still can't see any sensor data on IE Screen.
Would you please help me with this？ Thanks!

**Comment by JohnMeng** [comment]
What is your device?

**Comment by shijiong** [comment]
Lumia 1520. Wo. Can't believe that you reply so quickly. Are you here in China?

**Comment by JohnMeng** [comment]
Shang hai

I suggest you get to know whole structure of this project in the first.

**Comment by shijiong** [comment]
Wo. Thanks.
I completed the AzurePrep. The ehdevices and ehdevices are running. The LightSensor\cg4pbi\Aggregates\Alert are also running now. And i also deploy the WebSite to the Azure. Run Windows Phone application.
However, i can't see anydata.

**Comment by dinarisio** [comment]
Could you try to proactivly specify 'http' protocol for site in browser address list?

**Comment by shijiong** [comment]
![azure1](https://cloud.githubusercontent.com/assets/12369448/7647913/77c56f0e-fb0e-11e4-8547-f3834d586199.JPG)

**Comment by shijiong** [comment]
Oh, the state preview of my azure account can't display.
So, I wonder that whether my steps are correct?
First, run AzurePrep to achieve the configurations of Azure. Get the Web.Config file. Log on to Azure portal, start the four stream analysis jobs. Deploy Windows Phone application on device, and complete the connection cofig on device. Then deploy the WebSite Application to Azure.It informed me that "This web app has been successfully created". And does this means that i don't need to run the WebSite application locally? And after that , i can't see any data incoming on Azure

**Comment by dinarisio** [comment]
First, you can try using EHConsole tool to see if there is data coming to Event Hub.

**Comment by shijiong** [comment]
Hello, I tried your advice to run EHConsole. And get the following meaasges:
Starting worker to process partition: 0
Starting worker to process partition: 5
............................................................
Starting worker to process partition: 3
Waiting for start receiving messages: 7
Waiting for start receiving messages: 4
...........................................................
Waiting for start receiving messages: 0

And i can't see any other messages from my EHConsole. i Kept my Windows Phone applicaion Running .

**Comment by shijiong** [comment]
![zaure2](https://cloud.githubusercontent.com/assets/12369448/7648488/26ce3510-fb16-11e4-90a3-15d694f1cbf2.JPG)

**Comment by dinarisio** [comment]
It could take a couple of minutes before messages will show up, but looks like there i no messages.. What is your data source?

**Comment by shijiong** [comment]
I only run Windows Phone application. Not any other devices yet.
