### ISSUE TITLE
How to resolve "Unable to find version 0.13.3-build02496 of package Microsoft.ApplicationInsights.WindowsStore" Error

### ISSUE THREAD

**Issue by shijiong** [MSOpenTech/connectthedots#163]
Dear,
I Open WindowsIoTCorePi2 on Windows 10 Build 10074 with Visual Studio 2015 RC Enterprise, and VS can't build the solution because of the following reason. Would you please help me to fix this? Thanks!
![azure](https://cloud.githubusercontent.com/assets/12369448/7648861/10276044-fb1a-11e4-83f9-07f2b8cdea94.PNG)

**Comment by meapax** [comment]
I have W10 Build 10122 and experiencing the same issue.

**Comment by spyrossak** [comment]
Closed due to back of activity. Please re-open if needed.
