### ISSUE TITLE
CoC work items

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#165]
1.	Create and test 4 physical sensor devices (breadboarding, wiring, etc)
2.	Create code that will run on those 4 remote devices (BTLE + A/D + soil moisture sensor) to read the sensor
3.	Create the code or configuration documentation for connecting the 4 remote devices to 4 Pi via BTLE
4.	Create the code to run on the Pi for reading the data received over BTLE from the remote sensors
5.	Complete the end-to-end hardware + software setup, showing data arriving in an Azure EH from a remote soil moisture sensor.
6.	Complete any deployment scripts (e.g. deploy.cmd)
7.	Write basic documentation for how to recreate and deploy (bullets fine)
8.	Deliver 4 complete working kits to me.

**Comment by VladimirTsyshnatiy** [comment]
Hi, Lorenzo.


>> Create code that will run on those 4 remote devices (BTLE + A/D + soil moisture sensor) to read the sensor

I'm not sure I know what is  A/D. I suspect this can be Arduino, could you please clarify?

I do not have hardware for those devices, I can purchase missing parts.

Could you please confirm that my understanding is correct:

We take UART bluetooth module, connect it to the arduino(A/D?), connect soil moisture sensor and send data to raspberry pi with USB bluetooth dongle.


>> Create the code or configuration documentation for connecting the 4 remote devices to 4 Pi via BTLE?

So you actually need 4 kits of (uart bluetooth + arduino + soil moisture sensor)? + (raspberry pi + usb dongle)?

If so, I do not have this number of Pi's, arduino's, bluetooth modules and other parts.

I still can purchase them, but first I'd like to ensure I understood you correctly.

?Is it an option to take (1 arduino + 1 uart bluetooth + 4 soil moisture sensor) and send data to (1 raspberry pi + 1 usb dongle)??

In this case I have almost all necessary hardware.


>> Deliver 4 complete working kits to me.?

Do you mean delivering by mail (DHL and etc)?


Also I will merge Bluetooth branch to master when we will be clear with next steps and this task will be implemented, ok?

I'm not sure we need Arduino Mock in master branch, but a real sensor.


With regards, Vladimir.

________________________________

**Comment by spyrossak** [comment]
done
