### ISSUE TITLE
EHConsole enhancements

### ISSUE THREAD

**Issue by olivierbloch** [MSOpenTech/connectthedots#176]
Consumer group : 
   - EHConsole should NOT use the prefix Website when creating its consumer group when connecting to Event Hub.
   - EHConsole should delete the consumer group he created to monitor the event hub

Choice of Event Hub to monitor: For now the tool is hardcoded to monitor only ehdevices. We need to give the user the choice of monitoring the event hub of his choice

**Comment by dinarisio** [comment]
Upd. Choice of Event Hub to monitor is already implemented (in master only).

**Comment by olivierbloch** [comment]
Closing as EHConsole is NOT recreating a new consumer group but instead is using the default one, which is acceptable
