### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by markhenninger** [MSOpenTech/connectthedots#181]
After running the project for several days, the website opens several consumer group connections to the ehdevices and ehalerts event hubs.  Eventually the consumer group limit of 20 is exceeded, and the website can't get data.  I have to delete the "stale" consumer group connections periodically. Not sure if this is a code issue, or an issue with my deployment.

**Comment by dinarisio** [comment]
Fix was pushed to master today.

**Comment by spyrossak** [comment]
Had same problem. Fix from dinar seems like it should do the trick. Have deployed myself and will see. Closing issue. Reopen if problem reappears.

**Comment by markhenninger** [comment]
Worked for me. Thanks
