### ISSUE TITLE
Stream Analytics Aggregates and Alerts jobs degraded

### ISSUE THREAD

**Issue by spyrossak** [MSOpenTech/connectthedots#187]
On main website - temp average stopped showing up after a while. Reappeared after restarting SA job. Temp alerts not showing up.

**Comment by dinarisio** [comment]
JSON from Stream Analytics with multiple items have '}\r\n{' separator instead of '}{' before, so i added new workaround for this.

**Comment by spyrossak** [comment]
Stream Analytics added option in creating jobs for sending JSON as array or with line endings. Dinar fixed.
