### ISSUE TITLE
sensorEndpoints error in App.config

### ISSUE THREAD

**Issue by markhenninger** [MSOpenTech/connectthedots#190]
The two sensorEndpoints in \GatewayService\Gateway\Microsoft.ConnectTheDots.GatewayService\App.config cause a dot net error on Raspberry Pi. Removing one fixes the error and the service will run on Raspberry Pi.

**Comment by dinarisio** [comment]
Thanks for sharing. Looks like the cause of error is identical names of this endpoints - i've changed second to 'LocalForSocket2'.
Please let me know if it does not help.

**Comment by markhenninger** [comment]
That works.
