### ISSUE TITLE
Alerts in ConnectTheDotsIot

### ISSUE THREAD

**Issue by lukazorc** [MSOpenTech/connectthedots#211]
Hi, I tried the ConnectTheDotsIot example on Raspberry Pi 2 and it worked fine. But if I add alerts in the message send to Event Hubs the web site doesn't show neither the graph nor the alerts.
If before the message with the alerts I send some message without alerts, then the web site work fine, it shows the graph and the alerts.
If the first message that I send is with alerts then the ConnectTheDotsWebSite throws an exception (System.ArgumentOutOfRangeException) in the WebSocketEventProcessor.cs file on line 127 because SortedDataBuffer is Count=0. 

Is this normal or I'am doing something wrong?

The way I add the alerts in MainPage.cs is this:

ctdHelper = new ConnectTheDotsHelper(serviceBusNamespace: "xxx",
                eventHubName: "ehdevices",
                keyName: "xxx",
                key: "xxx",
                displayName: "xxx",
                organization: "xxx",
                location: "xxx",
                alerttype: "xxx", //if I comment this in all the code work fine...
                message: "xxx", //the message of the alarm
                sensorList: sensors);

**Comment by dinarisio** [comment]
Hello, thanks for detailed feedback.
I pushed fix to master. Please let me know if it would not work for you.

**Comment by lukazorc** [comment]
It works! Thank you!

**Comment by spyrossak** [comment]
Thanks!

Sent from my Windows Phone
________________________________
