### ISSUE TITLE
Unable to create azure resources for event hub

### ISSUE THREAD

**Issue by Pooja-B** [MSOpenTech/connectthedots#38]
I tried to create azure resources as 
cd ConnectTheDots\Azure\CloudDeploy\ConnecTheDotsCloudDeploy\bin\debug\
ConnectTheDotsCloudDeploy.exe –n <name> -ps <publishsettingsfile>

but when I run this command I am getting this error

Error:unrecognized argument: -n
Usage :ConnecttheDotsCloudDeploy -publishSettingFile <settingfile> [-NamePrefix <prefix>] [-Location <location>] [-website <websitedir>]

**Comment by toolboc** [comment]
Did you provide a value for -n and -ps?
For example: ConnectTheDotsCloudDeploy.exe –n MyNamespace -ps MyPusblishSettingsFile?

See documentation [here](https://github.com/MSOpenTech/connectthedots/blob/master/Azure/CloudDeploy/ConnectTheDotsCloudDeploy/Docs/Temp%20and%20Humidity%20Azure%20setup.md#create-azure-resources-for-event-hub)

 Also, did you cut and paste the command?  I have seen this be an issue before, try typing it out fully and let us know if that works =)

**Comment by Pooja-B** [comment]
It is solved now. Yes you are right ,Actually I was pasting the copied path from the explorer in cmd. Then I typed the complete path and again got an error. finally I  tried with getting into each directory one by one and it worked.
Thanks :)
