### ISSUE TITLE
Server error while creating website

### ISSUE THREAD

**Issue by Pooja-B** [MSOpenTech/connectthedots#39]
I created the website by following the same steps and published it but when running it I am getting the following error(The name I have given is "weatherstation")

Server Error in '/' Application.
EventHub names must conform to the following rules to be able to use it with EventProcessorHost: Must start with a letter or number, and can contain only letters, numbers, and the dash (-) character. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names. All letters in a container name must be lowercase. Must be from 3 to 63 characters long.
Parameter name: leaseContainerName 

[ArgumentException: EventHub names must conform to the following rules to be able to use it with EventProcessorHost: Must start with a letter or number, and can contain only letters, numbers, and the dash (-) character. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names. All letters in a container name must be lowercase. Must be from 3 to 63 characters long.
Parameter name: leaseContainerName]

**Comment by hallard** [comment]
Pooja
I had the same issue
replace in web.config
    `<add key="Microsoft.ServiceBus.EventHubDevices" value="EHDevices"/>
    <add key="Microsoft.ServiceBus.EventHubAlerts" value="EHAlerts"/>`
by
   `<add key="Microsoft.ServiceBus.EventHubDevices" value="ehdevices"/>
    <add key="Microsoft.ServiceBus.EventHubAlerts" value="ehalerts"/>`
all in lower case

**Comment by Pooja-B** [comment]
Thank you so much :)
