### ISSUE TITLE
web.config is modified by the application

### ISSUE THREAD

**Issue by rgardler** [MSOpenTech/connectthedots#4]
Azure\ConnectTheDotsWebSite\web.config is modified by ConnectTheDotsCloudDeploy.exe Since this is a source file it should not be modified by the application itself.

We should move to having a template in source and saving the modified version in our local config for the application.

**Comment by olivierbloch** [comment]
this is by design

**Comment by rgardler** [comment]
My issue is not with the design, it is with a file that gets modified by the code being in version control. This is bad practice because it means the file (at best) gets considerable churn and (at worst) produces unexpected side effects when someone does a git pull after such a change.

Local configurations should be kept local.
