### ISSUE TITLE
'truly' crosss platform API (was: Send Data API Format)

### ISSUE THREAD

**Issue by hallard** [MSOpenTech/connectthedots#40]
Hi there 
Is someone is able to show a example of sending data to the hub with a more "generic" way; IE not using mono or any other layer.

For example posting data to the hub just using curl or a browser URL ?

Thanks for your help

**Comment by ivanignatiev** [comment]
Hello @hallard 

Send Event method of REST API is described there : https://msdn.microsoft.com/en-us/library/azure/dn790664.aspx . Regarding the documentation this command should work :
```shell
curl -H 'Authorization: SharedAccessSignature sr={Service Bus Namespace}.servicebus.windows.net&sig={Url Encoded Shared Access Key}&se={Time Stamp with Shared Access Key expration}&skn={Shared Access Policy name}' -H 'Content-Type:application/atom+xml;type=entry;charset=utf-8' --data '{Event Data}' https://{Service Bus Namespace}.servicebus.windows.net/{Event Hub Name}/messages
```

https://gist.github.com/ivanignatiev/d8fca4ff8b3f729f7337

**Comment by olivierbloch** [comment]
Working on a JS sample running on node that uses the REST API. coming real soon
