### ISSUE TITLE
Carve out interfaces (e.g. ILogger) from GatewayAssembly

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#42]
need to separate interfaces from Gateway assembly, so we reduce dependencies

**Comment by dinarisio** [comment]
Would it be a separate library containing only interfaces?

**Comment by lt72** [comment]
yes, I see not other way

**Comment by dinarisio** [comment]
Library added, but looks like only ILogger is referenced outside Gateway for now.
