### ISSUE TITLE
DataIntakeLoader ctor does not check for various point of failures

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#43]
for example, this code:

Assembly ass = Assembly.LoadFrom( e.AssemblyPath );
                        Type handlerType = ass.GetType( e.TypeName );

                        IDataIntake dataIntake = ( IDataIntake )Activator.CreateInstance( handlerType );

should check for null on the return types

(at the time I opened this bug, MSDN was down, so check may not be needed)

**Comment by dinarisio** [comment]
Added exception catching - loading an assembly could thow, as well as CreateInstance. Also added mentioned null check to not add nulls to intakes list.

**Comment by lt72** [comment]
please check this in into the rftctr1 branch ASAP

**Comment by dinarisio** [comment]
Checked in already. However, Loader is waiting for a changes related to the endpoints abstraction.
