### ISSUE TITLE
error after publishing connectthedots

### ISSUE THREAD

**Issue by bdeepa** [MSOpenTech/connectthedots#44]
Hello,
Am getting the following error after publishing this website in azure.  Kindly help me to proceed further. 

![image](https://cloud.githubusercontent.com/assets/9347100/6239647/a990a640-b6ba-11e4-93c2-9370dcaa7e62.png)

Thank you!

**Comment by RobDolinMS** [comment]
What's the name of your EventHub ?

**Comment by bdeepa** [comment]
ehdevices & ehalerts

**Comment by bdeepa** [comment]
Hello Rob, I found my mistake in web.config file.
<add key="Microsoft.ServiceBus.EventHubDevices" value="EHDevices" />
 <add key="Microsoft.ServiceBus.EventHubAlerts" value="EHAlerts" /> 

changed to 
<add key="Microsoft.ServiceBus.EventHubDevices" value="ehdevices" />
<add key="Microsoft.ServiceBus.EventHubAlerts" value="ehalerts" />

Thank you!

**Comment by RobDolinMS** [comment]
Glad you solved it :)
