### ISSUE TITLE
Find betterEndPoint abstraction for gateway 

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#45]
Current endpoint abstraction for gateway 

        public bool SetEndpoint(ISensorEndpoint endpoint)

does not work very well across devices

find better abstraction or cut!

**Comment by dinarisio** [comment]
To fix it properly I need to understand what's wrong with current abstraction.
I comed up with it for realising the idea that just address of data source is needed, so we should not link endpoints with Data Intake modules and on other hand - to create more than one instance if needed. But, there are Data Intakes such as SerialPort that does not need any connection details, so they accept only empty endpoint data.
Bad case I see is when another Data Intake as python script comes to chain, so we need to somehow send endpoint data to it.

**Comment by dinarisio** [comment]
Lorenzo, could you please comment? May I leave this abstraction?
