### ISSUE TITLE
Change SignalDataArrival in favor of pure event patter

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#46]
The only reason why we need SignalDataArrival is to invoke the event, 
find another way

**Comment by dinarisio** [comment]
As I see, it's used in CoreTest only. Anyway, we can send instead of pure gateway's enqueue method another one:
                    if (onDataArrival != null)
                    {
                        OnDataToEnqueue = 
                            data => {
                                onDataArrival(data);
                                return enqueue(data);
                            };
                    }
                    else
                        OnDataToEnqueue = enqueue;
                    dataIntake.Start(OnDataToEnqueue);

**Comment by lt72** [comment]
I like that
