### ISSUE TITLE
Remove handcoded paths from project 

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#47]
<add name="SerialPortSensor" 
         type="SerialPortListener.SerialPortListenerThread" 
         assemblyPath="..\..\SLAC\connectthedots1\Devices\Gateways\GatewayService\DataIntakes\SerialPortListener\bin\Debug\SerialPortListener.dll"/>

**Comment by dinarisio** [comment]
Problem that service is installed to system directory, so related to source directory paths would be broken. Will think about good solution. For now I think just to leave
assemblyPath="<Enter full path to the assembly here>".

**Comment by lt72** [comment]
I like that

**Comment by dinarisio** [comment]
In rfctr1 already.
