### ISSUE TITLE
BatchSenderThread will wait for another heap of messages before send

### ISSUE THREAD

**Issue by dinarisio** [MSOpenTech/connectthedots#48]
BatchSenderThread would not send messages if new event popped before we WaitOne it and after encounting number of items to queue.

**Comment by lt72** [comment]
I commented out the Sleep again because I cannot repro the issue and I want to see it failing

**Comment by dinarisio** [comment]
I tried to find parameters to make it fail all the time, and in my machine it failes pretty often when i use small number(2-20) of test iterations. The thing I used in trying to challange code is to send message while BatchSenderThread is sending previous heap. And in some cases it will not able to reach for event on _doWork.
I did not know very much about an AutoResetEvent, but it turned out that there is a simple solution - to set timeout parameter at WaitOne, so regardless of message rate it would reach every x seconds. If x is not very small, it would not affect performance. What do you think about adding it?

**Comment by lt72** [comment]
I found the race condition and set up a timeout to resolve it, for now...

**Comment by lt72** [comment]
assigned this one to myself
