### ISSUE TITLE
After a task is popped from the gateway queue, we discard it if we fail to process it

### ISSUE THREAD

**Issue by lt72** [MSOpenTech/connectthedots#49]
After a task is popped from the gateway queue, we discard it if we fail to process it

// process all messages that have not been processed yet
                        while (--count >= 0)
                        {
                            var t = _DataSource.TryPop();  <<<<<<<<<<<<<<<  HERE

                            Debug.Assert( _outstandingTasks >= 0 ); 

                            bool added = false;
                            try
                            {
                                // increment outstanding task count but be ready to decrement if we fail to add to the queue
                                Interlocked.Increment( ref _outstandingTasks );

                                Debug.Assert( tasks != null );

                                tasks.Add(
                                    t.ContinueWith<Task>( popped =>
                                    {
                                        Interlocked.Decrement( ref _outstandingTasks );

                                        // because the outstanding task counter is incremented before 
                                        // adding, we should never incur a negative count 
                                        Debug.Assert( _outstandingTasks >= 0 );

                                        if( popped.Result.IsSuccess )
                                        {
                                            if( _DataTransform != null )
                                            {
                                                return _DataTarget.SendMessage( _DataTransform( popped.Result.Result ) );
                                            }
                                            if( _SerializedData != null )
                                            {
                                                return _DataTarget.SendSerialized( _SerializedData( popped.Result.Result ) );
                                            }
                                        }
                                        else
                                        {
                                            throw new Exception( );
                                        }
                                        return popped;
                                    } )
                                );

                                // the only case when we do not get here is if List.Add fails (tasks.Add) or
                                // if the task engine fails Task.ContinueWith (t.ContinueWith)
                                added = true;
                            }
                            catch
                            {
                                if( !added )
                                {
                                    Interlocked.Decrement( ref _outstandingTasks );   
                                }

                                //
                                // TODO: Issue 
                                //
                                throw;
                            }
                        }

**Comment by dinarisio** [comment]
For now decided to give message back to the queue because we don't know status of other sending tasks.

**Comment by dinarisio** [comment]
Should we try to send it right there without queueing again?

**Comment by lt72** [comment]
no, lets' just close this
