### ISSUE TITLE
AzurePrep: Check service name validity

### ISSUE THREAD

**Issue by rgardler** [MSOpenTech/connectthedots#5]
ConnectTheDotsCloudDeploy requires that a name be submitted. This name has fairly stringent constraingts. Test for them before starting to create the service otherwise we get a partially complete service:

We need to check for (at least):
  - only letters and numbers – no spaces, dashes, underlines, etc
  - less than 17 characters (storage account names must be < 24 characters and we add "storage" to the end)

**Comment by lt72** [comment]
Check for length and invalid characters only at input time. Do NOT check with the backend for existing name.

**Comment by dinarisio** [comment]
Done at AzurePrepUpdates branch.
