### ISSUE TITLE
Fix Socket dataintake in new GatewayService

### ISSUE THREAD

**Issue by spyrossak** [MSOpenTech/connectthedots#67]

**Comment by dinarisio** [comment]
There were couple of issues at WensnPiVS01.py. Also I've updated Socket adapter to make it retry connection when already used socket dies.

**Comment by lt72** [comment]
We need to make the pythin socket script a client and the gateway DataIntake a server

**Comment by spyrossak** [comment]
Splitting into two issues, closing first, opening second
