### ISSUE TITLE
Change name of RaspberryPiGateway to Gateway?

### ISSUE THREAD

**Issue by rgardler** [MSOpenTech/connectthedots#7]
There is nothing specific, other than startup scripts, to the RaspberryPi within the Gateway. In fact during testing it is easier to use a Windows machine. Some folks might even prefer to use a Windows machine as the gateway.

For example, I have a Dell Windows 8 Tablet as a controller for my Hue lights in some of my rooms. Rather than install a Pi in these rooms I'd rather use the existing tablet as the Gateway.

It therefore seems to make sense to separate out the startup scripts from the Gateway code. THis would give us both a "RaspberryPiGateway" and a "Gateway" artifact.

Thoughts?

**Comment by olivierbloch** [comment]
We just updated the project architecture to ease the addition of more devices but for now we are keeping the code for the Raspberry Pi Gateway project under this name. Once we have several devices using the same piece of code we will consider having a generic code folder added that several devices projects can use code from.
