### ISSUE TITLE
Suggestion: convert Windows to Unix line endings before copying to Pi

### ISSUE THREAD

**Issue by spyrossak** [MSOpenTech/connectthedots#80]
Prefer not to need dos2unix to be loaded on Pi, per the current deployment scripts.

**Comment by lt72** [comment]
conversion needs to be done BEFORE deploying files to R-pi board

**Comment by dinarisio** [comment]
Done at AzurePrepUpdates branch (just as all my updates today there). Worked for me, but suggest to test as well.
