### ISSUE TITLE
CreateWebConfig: display existing namespaces

### ISSUE THREAD

**Issue by spyrossak** [MSOpenTech/connectthedots#94]
CreateWebConfig should only proceed if the user has already created a namespace in Azure. Currently the app asks user to provide a namespace name, unrelated to what they have. Instead, it should advise the user that this will create a web.config file to create a ConnectTheDots website that accesses event hubs in their subscription. It should present a numbered list to the user of namespaces they have created in Azure, and ask them to pick a number. One of the options should be to quit without proceeding.

**Comment by dinarisio** [comment]
Done at AzurePrepUpdates branch.
