### ISSUE TITLE
CreateWebConfig: creating config file

### ISSUE THREAD

**Issue by spyrossak** [MSOpenTech/connectthedots#95]
After specifying the namespace, the app finishes with no notice to the user of what it did. The app should tell the user what it is doing on the console, then what it did, including the location of the web.config file, which should be on the user's desktop. Finally, the app should indicate "Hit Enter to quit" and wait for user input.

**Comment by olivierbloch** [comment]
Actually I would say that it'd be great to NOT have to enter the service bus namespace manually but instead to list the existing namespaces and let the user choose in the list. This way we avoid issues and prevent the user to have to do any other entries

**Comment by dinarisio** [comment]
Done at AzurePrepUpdates branch.
