### ISSUE TITLE
AZURESTREAMANALYTICS: Create azure stream analytics not working

### ISSUE THREAD

**Issue by Anjoli** [MSOpenTech/connectthedots#99]
Hi, I was trying to create all the setup in one go but as soon as i define AZURESTREAMANALYTICS started getting compilation errors.I fix those errors at my end then try to execute.
But getting exception at line 185:
var groupCreateResponse = groupCreateRequest.GetResponse();

Exception:
The remote server returned an error: (401) Unauthorized.

Kindly help.

**Comment by dinarisio** [comment]
Initial version implemented at ehconsoleUpd branch.

**Comment by dinarisio** [comment]
Merged with master - welcome to check this out.
